package com.openmed.openmedkit.merge

import java.util.regex.Pattern

/**
 * Regex pattern metadata for detecting complete PII semantic units.
 */
data class SemanticUnitPattern(
    val pattern: String,
    val entityType: String,
    val priority: Int = 0,
    val captureGroup: Int? = null,
    val multiline: Boolean = false,
    val baseScore: Float = 0.5f,
    val contextBoost: Float = 0.35f,
    val contextWords: List<String> = emptyList(),
    val validator: ((String) -> Boolean)? = null,
) {
    val regex: Pattern = Pattern.compile(
        pattern,
        Pattern.CASE_INSENSITIVE or if (multiline) Pattern.MULTILINE else 0,
    )
}

/**
 * A semantic PII span detected by a pattern scan.
 */
data class SemanticUnitMatch(
    val start: Int,
    val end: Int,
    val entityType: String,
    val score: Float,
    val validated: Boolean,
)

object DefaultPiiPatterns {
    private val dateContextWords = listOf(
        "dob",
        "birth",
        "born",
        "date of birth",
        "birthdate",
        "deceased",
        "died",
        "admitted",
        "discharged",
    )

    private val phoneContextWords = listOf(
        "phone",
        "tel",
        "telephone",
        "cell",
        "mobile",
        "fax",
        "call",
        "contact",
    )

    val patterns: List<SemanticUnitPattern> = listOf(
        SemanticUnitPattern(
            "\\bDOB:\\s*(\\d{1,2}/\\d{1,2}/\\d{2,4})\\b",
            entityType = "date_of_birth",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.97f,
            contextBoost = 0.02f,
            contextWords = listOf("dob", "date of birth", "birthdate"),
        ),
        SemanticUnitPattern(
            "^DOB\\s*\$\\n(\\d{1,2}/\\d{1,2}/\\d{2,4})(?=\\n|\$)",
            entityType = "date_of_birth",
            priority = 15,
            captureGroup = 1,
            multiline = true,
            baseScore = 0.97f,
            contextBoost = 0.02f,
            contextWords = listOf("dob", "date of birth", "birthdate"),
        ),
        SemanticUnitPattern(
            "\\bSSN:\\s*(\\d{3}-\\d{2}-\\d{4})\\b",
            entityType = "ssn",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.96f,
            contextBoost = 0.02f,
            contextWords = listOf("ssn", "social security", "social security number"),
        ),
        SemanticUnitPattern(
            "\\bMRN:\\s*([A-Z0-9][A-Z0-9-]{4,})\\b",
            entityType = "medical_record_number",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("mrn", "medical record", "record number"),
        ),
        SemanticUnitPattern(
            "\\bAddress:\\s*([^,\\n]+(?:,\\s*[^,\\n]+)*?)(?=,\\s*(?:Phone|Email|Insurance ID|Driver License|Passport|Emergency Contact|Employer|Employee ID|Bank Account|Routing):|\$)",
            entityType = "street_address",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("address", "street", "residence", "lives at"),
        ),
        SemanticUnitPattern(
            "\\bPhone:\\s*(\\(\\d{3}\\)\\s*\\d{3}[-.\\s]?\\d{4})\\b",
            entityType = "phone_number",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("phone", "telephone", "contact"),
        ),
        SemanticUnitPattern(
            "\\bEmail:\\s*([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,})\\b",
            entityType = "email",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.97f,
            contextBoost = 0.02f,
            contextWords = listOf("email", "e-mail", "mail"),
        ),
        SemanticUnitPattern(
            "\\bInsurance ID:\\s*([A-Z0-9][A-Z0-9-]{4,})\\b",
            entityType = "insurance_id",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("insurance", "policy", "coverage", "payer"),
        ),
        SemanticUnitPattern(
            "\\bMember ID\\s*:?[\\t ]*([A-Z0-9][A-Z0-9-]{4,})\\b",
            entityType = "insurance_id",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("insurance", "member id", "policy", "coverage", "payer"),
        ),
        SemanticUnitPattern(
            "\\bInsurance:\\s*[^\\n]*?Member ID\\s*:?[\\t ]*([A-Z0-9][A-Z0-9-]{4,})\\b",
            entityType = "insurance_id",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("insurance", "member id", "policy", "coverage", "payer"),
        ),
        SemanticUnitPattern(
            "\\bBank Account:\\s*([A-Z0-9][A-Z0-9-]{5,})\\b",
            entityType = "account_number",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("bank account", "account", "banking"),
        ),
        SemanticUnitPattern(
            "\\bAccount\\s*#?:\\s*([A-Z0-9][A-Z0-9-]{4,})\\b",
            entityType = "account_number",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.95f,
            contextBoost = 0.03f,
            contextWords = listOf("account", "account number"),
        ),
        SemanticUnitPattern(
            "\\bRouting:\\s*(\\d{9})\\b",
            entityType = "routing_number",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.94f,
            contextBoost = 0.03f,
            contextWords = listOf("routing", "aba", "bank"),
        ),
        SemanticUnitPattern(
            "\\bNPI\\s*:?[\\t ]*(\\d{10})\\b",
            entityType = "npi",
            priority = 14,
            captureGroup = 1,
            baseScore = 0.94f,
            contextBoost = 0.03f,
            contextWords = listOf(
                "npi",
                "national provider",
                "provider number",
                "provider id",
                "provider identifier",
            ),
        ),
        SemanticUnitPattern(
            "\\b\\d{4}-\\d{2}-\\d{2}\\b",
            entityType = "date",
            priority = 10,
            baseScore = 0.6f,
            contextBoost = 0.3f,
            contextWords = dateContextWords,
        ),
        SemanticUnitPattern(
            "\\b\\d{1,2}/\\d{1,2}/\\d{2,4}\\b",
            entityType = "date",
            priority = 9,
            baseScore = 0.6f,
            contextBoost = 0.3f,
            contextWords = dateContextWords,
        ),
        SemanticUnitPattern(
            "\\b\\d{1,2}-\\d{1,2}-\\d{2,4}\\b",
            entityType = "date",
            priority = 9,
            baseScore = 0.6f,
            contextBoost = 0.3f,
            contextWords = dateContextWords,
        ),
        SemanticUnitPattern(
            "\\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \\d{1,2},? \\d{4}\\b",
            entityType = "date",
            priority = 8,
            baseScore = 0.7f,
            contextBoost = 0.25f,
            contextWords = dateContextWords,
        ),
        SemanticUnitPattern(
            "\\b\\d{1,2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \\d{4}\\b",
            entityType = "date",
            priority = 8,
            baseScore = 0.7f,
            contextBoost = 0.25f,
            contextWords = dateContextWords,
        ),
        SemanticUnitPattern(
            "\\b\\d{3}-\\d{2}-\\d{4}\\b",
            entityType = "ssn",
            priority = 10,
            baseScore = 0.3f,
            contextBoost = 0.55f,
            contextWords = listOf(
                "ssn",
                "social security",
                "social security number",
                "ss#",
                "ss number",
            ),
            validator = PiiValidators::validateSSN,
        ),
        SemanticUnitPattern(
            "\\b\\d{3}\\s\\d{2}\\s\\d{4}\\b",
            entityType = "ssn",
            priority = 9,
            baseScore = 0.3f,
            contextBoost = 0.55f,
            contextWords = listOf(
                "ssn",
                "social security",
                "social security number",
                "ss#",
                "ss number",
            ),
            validator = PiiValidators::validateSSN,
        ),
        SemanticUnitPattern(
            "\\b\\(\\d{3}\\)\\s*\\d{3}[-.\\s]?\\d{4}\\b",
            entityType = "phone_number",
            priority = 9,
            baseScore = 0.6f,
            contextBoost = 0.3f,
            contextWords = phoneContextWords,
            validator = PiiValidators::validatePhoneUS,
        ),
        SemanticUnitPattern(
            "\\b\\d{3}[-.\\s]\\d{3}[-.\\s]\\d{4}\\b",
            entityType = "phone_number",
            priority = 8,
            baseScore = 0.5f,
            contextBoost = 0.35f,
            contextWords = phoneContextWords,
            validator = PiiValidators::validatePhoneUS,
        ),
        SemanticUnitPattern(
            "\\b\\d{10}\\b",
            entityType = "npi",
            priority = 6,
            baseScore = 0.15f,
            contextBoost = 0.65f,
            contextWords = listOf(
                "npi",
                "national provider",
                "provider number",
                "provider id",
                "provider identifier",
            ),
            validator = PiiValidators::validateNPI,
        ),
        SemanticUnitPattern(
            "\\b\\d{10}\\b",
            entityType = "phone_number",
            priority = 5,
            baseScore = 0.2f,
            contextBoost = 0.5f,
            contextWords = phoneContextWords,
            validator = PiiValidators::validatePhoneUS,
        ),
        SemanticUnitPattern(
            "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b",
            entityType = "email",
            priority = 10,
            baseScore = 0.9f,
            contextBoost = 0.1f,
            contextWords = listOf("email", "e-mail", "contact", "mail"),
        ),
        SemanticUnitPattern(
            "\\b\\d{5}(?:-\\d{4})?\\b",
            entityType = "postcode",
            priority = 7,
            baseScore = 0.4f,
            contextBoost = 0.45f,
            contextWords = listOf("zip", "zipcode", "zip code", "postal", "postal code"),
        ),
        SemanticUnitPattern(
            "\\b\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}[-\\s]?\\d{4}\\b",
            entityType = "credit_debit_card",
            priority = 8,
            baseScore = 0.4f,
            contextBoost = 0.4f,
            contextWords = listOf(
                "card",
                "credit",
                "debit",
                "visa",
                "mastercard",
                "amex",
                "discover",
                "payment",
            ),
            validator = PiiValidators::validateLuhn,
        ),
        SemanticUnitPattern(
            "\\b(?:MRN|mrn)[:\\s#]*\\d{6,10}\\b",
            entityType = "medical_record_number",
            priority = 9,
            baseScore = 0.8f,
            contextBoost = 0.15f,
            contextWords = listOf(
                "medical record",
                "patient id",
                "patient number",
                "record number",
            ),
        ),
        SemanticUnitPattern(
            "\\b[A-Z]{2,3}\\d{6,9}\\b",
            entityType = "medical_record_number",
            priority = 5,
            baseScore = 0.3f,
            contextBoost = 0.5f,
            contextWords = listOf(
                "mrn",
                "medical record",
                "patient id",
                "patient number",
                "record number",
            ),
        ),
        SemanticUnitPattern(
            "\\b\\d{1,5}\\s+[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*\\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct|Way)\\b",
            entityType = "street_address",
            priority = 7,
            baseScore = 0.7f,
            contextBoost = 0.2f,
            contextWords = listOf(
                "address",
                "street",
                "resides",
                "residence",
                "lives at",
                "located at",
            ),
        ),
        SemanticUnitPattern(
            "\\b(?:account number|account #|acct\\.|acct|account)[:\\s#-]*[A-Z0-9][A-Z0-9-]{5,23}\\b",
            entityType = "account_number",
            priority = 8,
            baseScore = 0.75f,
            contextBoost = 0.15f,
            contextWords = listOf("account", "acct", "account number", "bank", "billing"),
        ),
        SemanticUnitPattern(
            "\\b(?:https?://)?(?:www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(?:/[^\\s]*)?\\b",
            entityType = "url",
            priority = 8,
            baseScore = 0.8f,
            contextBoost = 0.15f,
            contextWords = listOf("url", "website", "link", "webpage"),
        ),
        SemanticUnitPattern(
            "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b",
            entityType = "ipv4",
            priority = 7,
            baseScore = 0.6f,
            contextBoost = 0.3f,
            contextWords = listOf("ip", "ip address", "address", "server", "host"),
        ),
        SemanticUnitPattern(
            "\\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\\b",
            entityType = "ipv6",
            priority = 8,
            baseScore = 0.85f,
            contextBoost = 0.15f,
            contextWords = listOf("ip", "ipv6", "ip address", "address", "server", "host"),
        ),
        SemanticUnitPattern(
            "\\b(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}\\b",
            entityType = "mac_address",
            priority = 8,
            baseScore = 0.75f,
            contextBoost = 0.2f,
            contextWords = listOf("mac", "mac address", "hardware address"),
        ),
    )

}
